trigger: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  always: true
  branches:
    include:
    - backend/main
    - backend/dev
    - backend/feature/*

pool:
  vmImage: 'windows-latest'

variables:
  projectsRoot: 'src/'
  umbracoProjectName: 'Umbraco.Headless.Demo.Web'
  buildConfiguration: 'Release'
  boundedContext: 'demos'
  serviceName: 'headless-demo'
  terraformVersion: 1.1.7
  serviceVariableGroupFormat: '{0}-global-{1}' # '{boundedContext}-global-{environment}'
  serviceConnectionNameFormat: 'Infra-{0}-global-{1}' # 'Infra-{environment}-global-{boundedContext}'

jobs:
  - job: reset_dev
    displayName: Reset dev
    steps:
      - task: AzureAppServiceManage@0
        displayName: 'Stop App Service'
        inputs:
          azureSubscription: 'Infra-Dev-global-Demos'
          Action: 'Stop Azure App Service'
          WebAppName: 'azapp-dev-demos-headless-demo-umbraco'
      
      - task: PowerShell@2
        displayName: 'Restore database'
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Hello World"
      - task: AzureAppServiceManage@0
        displayName: 'Stop App Service'
        inputs:
          azureSubscription: 'Infra-Dev-global-Demos'
          Action: 'Start Azure App Service'
          WebAppName: 'azapp-dev-demos-headless-demo-umbraco'